In [11]:
import numpy as np

def softmax(x):
    x = x - np.max(x, axis=1, keepdims=True)
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

In [13]:
def compute_attention(sentence):
    tokens = sentence.split()
    np.random.seed(42)
    X = np.random.rand(len(tokens), 4)
    d_k = X.shape[1]
    W_Q = np.random.rand(d_k, d_k)
    W_K = np.random.rand(d_k, d_k)
    W_V = np.random.rand(d_k, d_k)
    Q = np.dot(X, W_Q)
    K = np.dot(X, W_K)
    V = np.dot(X, W_V)
    scores = np.dot(Q, K.T) / np.sqrt(d_k)
    weights = softmax(scores)
    output = np.dot(weights, V)
    return tokens, scores, weights, output


In [19]:
def run():
    sentence = input("Enter sentence: ")
    if sentence.strip() == "":
        print("Empty input!")
        return
    tokens, scores, weights, output = compute_attention(sentence)
    print("\nTOKENS:")
    print(tokens)
    print("\nATTENTION SCORES:")
    print(scores)
    print("\nATTENTION WEIGHTS:")
    print(weights)
    print("\nOUTPUT (CONTEXT VECTORS):")
    print(output)

if __name__ == "__main__":
    run()

Enter sentence:  What are the symptoms of diabetes



TOKENS:
['What', 'are', 'the', 'symptoms', 'of', 'diabetes']

ATTENTION SCORES:
[[3.81569598 2.16432635 3.31043181 1.66505512 2.16250518 1.94349674]
 [1.5268309  0.8539498  1.28901787 0.6559243  0.86567996 0.77597485]
 [2.78409829 1.60056975 2.4070056  1.19349674 1.57429535 1.41569101]
 [2.08076504 1.22825882 1.91969344 0.96410712 1.18130679 1.08980352]
 [2.26906749 1.29383256 1.98760138 1.00001213 1.28643095 1.16048136]
 [2.1314829  1.23399703 1.92809952 0.97963544 1.2113224  1.11076223]]

ATTENTION WEIGHTS:
[[0.44311197 0.08498314 0.26734991 0.05158246 0.08482851 0.06814401]
 [0.26987803 0.1377016  0.21275837 0.11296336 0.13932637 0.12737227]
 [0.36381894 0.11140005 0.24952613 0.07414738 0.1085112  0.09259629]
 [0.29559931 0.12602731 0.25162333 0.09677096 0.12024684 0.10973225]
 [0.3207981  0.12097417 0.24209879 0.0901754  0.12008207 0.10587147]
 [0.3031772  0.12357294 0.24738209 0.09581986 0.1208025  0.10924541]]

OUTPUT (CONTEXT VECTORS):
[[0.46915817 1.14134205 1.15529093 0.84433